project_id = "lbnziztopednzuzucdqi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.send-ticket-notification]
verify_jwt = false

[functions.send-registration-notification]
verify_jwt = false

[functions.send-approval-notification]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-work-notification]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.send-invoice-reminders]
verify_jwt = false

[functions.create-invoice-payment]
verify_jwt = false

[functions.verify-invoice-payment]
verify_jwt = false

[functions.send-resident-invitation]
verify_jwt = false

[functions.parse-payment-slips]
verify_jwt = false